---
- name: make sure that older packages are not installed
  apt:
    name: "{{ item }}"
    state: absent
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default(3600) }}"
  with_items:
    - "docker"
    - "docker-engine"
    - "docker.io"

- name: install required packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default(3600) }}"
  with_items:
    - "apt-transport-https"
    - "ca-certificates"
    - "curl"
    - "software-properties-common"
    - "python-pip"

- name: install docker-py
  pip:
    name: docker-py
    state: present

- name: add docker.io repository apt_key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: present

- name: enable docker.io apt repository
  apt_repository:
    repo: "https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes

- name: install docker
  apt:
    name: docker-ce-{{ docker.version }}
    state: present
    update_cache: yes
    cache_valid_time: "{{ apt_cache_valid_time | default(3600) }}"
