---

- import_tasks: install_yum.yml
  when: ansible_pkg_mgr == "yum"

- import_tasks: install_apt.yml
  when: ansible_pkg_mgr == "apt"

- import_tasks: configure_yum.yml
  when: ansible_pkg_mgr == "yum"

  #- import_tasks: configure_apt.yml
  #when: ansible_pkg_mgr == "apt"
